export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOADED = 'USER_LOADED';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const AUTH_ERROR = 'AUTH_ERROR';
export const USER_LOADING = 'USER_LOADING';

export const ORDERS_CREATE_FAIL = 'ORDERS_CREATE_FAIL'
export const ORDERS_LOADED = 'ORDERS_LOADED'
export const ORDERS_LOADING = 'ORDERS_LOADING'
export const ORDERS_CREATE = 'ORDERS_CREATE'
export const ORDERS_LOAD_FAIL = 'ORDERS_LOAD_FAIL'

export const PRODUCTS_LOADING_START = 'PRODUCTS_LOADING_START'
export const PRODUCTS_LOADED = 'PRODUCTS_LOADED'
export const PRODUCTS_CREATED = 'PRODUCTS_CREATED'
export const PRODUCTS_CREATED_FAIL = 'PRODUCTS_CREATED_FAIL'
export const PRODUCTS_LOADING_FAIL = 'PRODUCTS_LOADING_FAIL'
export const ORDER_STATUS_UPDATED = 'ORDER_STATUS_UPDATED'
export const ORDER_STATUS_UPDATE_FAIL = 'ORDER_STATUS_UPDATE_FAIL'

export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'


